@startuml DiagramaDeClases

Jugador -d-|> Persona
Entrenador -d-|> Persona
Jugador "6...20"-u-o "1    " Equipo
Entrenador "1" -u-o "*" Equipo
Partido "1" o-d- "2" Equipo 
Registro "1" -u-o Equipo 

class Equipo{
    - nombre: string
    - capitan: string
}

class Persona{
    - nombre: string
    - telefono: int
    - direccion: string
}

class Registro{
    - faltas:int
    - puntos: int
    - victorias: int
    - derrotas: int
}

class Jugador{
    - capitan: bool
    - numero: int
    - posicion: string
}

class Entrenador{
    - acreditacion:int
    - experiencia:string
}

class Partido{
    - localidad: string
    - puntuacion: int
}

@enduml